services:
  - type: web
    name: backend
    env: node
    repo: https://github.com/miqs1992/typer2026
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

  - type: web
    name: frontend
    env: static
    repo: https://github.com/miqs1992/typer2026
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist/frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: postgres
    plan: free
