services:
  - type: web
    name: backend
    runtime: node
    repo: https://github.com/miqs1992/typer2026
    plan: free
    region: frankfurt
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

  - type: web
    name: frontend
    runtime: static
    repo: https://github.com/miqs1992/typer2026
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist/eurotyper2026/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: postgres
    plan: free
    region: frankfurt
