services:
  - type: web
    name: backend
    runtime: node
    repo: https://github.com/miqs1992/typer2026
    plan: free
    region: frankfurt
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

  - type: web
    name: frontend
    runtime: static
    repo: https://github.com/miqs1992/typer2026
    autoDeployTrigger: commit
    rootDir: frontend
    buildCommand: >
      sed -i "s|__BACKEND_URL__|$BACKEND_URL|g" src/environments/environment.ts &&
      sed -i "s|__CLERK_PUBLIC_KEY__|$CLERK_PUBLIC_KEY|g" src/environments/environment.ts &&
      npm install && 
      npm run build
    staticPublishPath: dist/eurotyper2026/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: postgres
    plan: free
    region: frankfurt
