POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "miqs1992@gmail.com",
  "firstName": "Wojtek",
  "lastName": "Mikusek",
  "password": "Test123!",
  "passwordConfirmation": "Test123!"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "miqs1992@gmail.com",
  "password": "Test123!"
}

> {%
    const token = response.body.access_token
    client.global.set('backendToken', token)
%}

###
GET http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer {{backendToken}}

###
POST http://localhost:3000/rounds
Content-Type: application/json

{
  "name": "Group 1",
  "order": 1,
  "scoreFactor": 1.0,
  "stage": "GROUP"
}